.TH TSC 6 "August 9, 2015"
.SH NAME
tsc \- a Jump and Run game like Super Mario World
.SH SYNOPSIS
.B tsc
.RI [ options ] "
.br
.SH DESCRIPTION
This manual page documents briefly the
.B tsc
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtsc\fP  is a 2D sidecrolling platform game, with a rich set of graphics,
music, and an advanced level editor that allows you to create your own levels.
The level editor allows for in-game scripting so there are no borders apart
from your imagination.

The project is a fork of SMC, which is not developed actively anymore. Note
this is not merely a continuation of SMC, but we have our own goals and design
principles we are slowly integrating into both the codebase and the artwork.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long options
starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-d, \-\-debug
Enable debug modes with the options : game performance.
.TP
.B \-l, \-\-level
Load the given level.
.TP
.B \-w, \-\-world
Load the given world.
.SH AUTHOR
tsc was written by FluXy, Boder and now forked by  The TSC Contributors.
.PP
This manual page was written by Muammar El Khatib <muammar@debian.org>,
for the Debian project (but may be used by others).
